### ISSUE TITLE
Additional parts

### ISSUE THREAD

**Issue by PatrickLouys** [PatrickLouys/no-framework-tutorial#2]
"Education is the key here. You want to show your readers the whys of how a framework operates. Demonstrate areas of responsibility - accepting input, figuring out how to handle the request, validating input in the context of the request, handling the request, operating request-specific business logic, gathering of data as a result of the logic, then presenting the data to the user." - Charles

**Comment by J7mbo** [comment]
I think a key extra requirement here for this to be useable for people would be: **security**. As in, sort of ACL. If this were in the tutorial, that'd basically be everything needed to start on a full web application. Although it's a large topic...

**Comment by HassanAlthaf** [comment]
@J7mbo agreed.

**Comment by PatrickLouys** [comment]
I have a lot of things going on at the moment, but I'll definitely keep expanding the tutorial to include security and other important things as soon as I can find some time. It's still a work in progress.

**Comment by J7mbo** [comment]
Lazy bastard.

**Comment by HassanAlthaf** [comment]
@J7mbo Lets take over his repository. @PatrickLouys We offer you a takeover bid of US$0.0000000000000000000000001 which is ≈ $0.

**Comment by dnixx** [comment]
Really well explained! Care to share a little about how the book is progressing? :)

**Comment by PatrickLouys** [comment]
@dnixx I'm about 30 pages in, hopefully I'll be able to release something at the end of the year.

**Comment by basherr** [comment]
@PatrickLouys Any updates on Security?

**Comment by PatrickLouys** [comment]
@basherr Not yet, it's hard to find time to update the tutorial. They need to be part of a relevant chapter.

What I want to cover as part of the tutorial is at least XSS, CSRF and injection. In the meantime I recommend reading ircmaxell's blogposts on them.

**Comment by basherr** [comment]
@PatrickLouys Desperately need the book..

**Comment by PatrickLouys** [comment]
Covered those topics in the [book](http://patricklouys.com/professional-php/)
