### ISSUE TITLE
Could not make Example\Template\FrontendTwigRenderer: Class Example\Template\FrontendTwigRenderer does not exist

### ISSUE THREAD

**Issue by mr-lanholmes** [PatrickLouys/no-framework-tutorial#28]
Hi. I went through one by one of your tutorial on Windows and it works well. But when I tried to hosted it on Linux (Ubuntu) It shows this error.
![error](https://cloud.githubusercontent.com/assets/2654430/8635974/be83181a-2877-11e5-8c0e-9eb8ea8ec66d.JPG)

**Comment by mr-lanholmes** [comment]
Hi there. Anyone there.. Please help me... @PatrickLouys

**Comment by PatrickLouys** [comment]
Come to http://chat.stackoverflow.com/rooms/11/php and ping me (Patrick) so we can work this out. An issue is not really the place for this.
