### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by PatrickLouys** [PatrickLouys/no-framework-tutorial#30]
revisit the "routing" and "dynamic pages" chapters and then do a chapter on DB handling

**Comment by Zvax** [comment]
I've had to use a markdown parser (I used Parsedown) to actually pass md files through twig in a way that they would render correctly in the browser. Was that left as an exercise for the reader? Should there be a section on how to integrate that markdown parser to the FilePageReader?

**Comment by philsown** [comment]
It could be a new PageReader implementation with a simple PDO object passed in (which could obviously be an implementation and concrete...) Or abstracted classes for the various tables... Yeah, the rabbit hole goes deep. But the way you build on things from chapter to chapter I feel like it could be started with a simple implementation and piled on later.

```php
<?php

namespace Example\Page;
// use stuff ...

class DbPageReader implements PageReader {
    private $db;

    public function __construct(Database $db)
    {
        $this->db = $db;
    }

    public function __readBySlug(string $slug) : string
    {
        $page = $this->db->query('SELECT * FROM pages WHERE slug = ?', ['slug' => $slug]);
        return $page->body;
    }
}
```

**Comment by ellisgl** [comment]
I've been using "my own" wrapper: https://github.com/ellisgl/GeekLab-GLPDO

The structure I use is as follows:
    src\
        Db\
            Connect\
                {databasename}.php
            Model\
                ---Models are data that are manipulated---
            Query\ ---Query files only have single queries---
               {tablename}.php
