### ISSUE TITLE
.htaccess File for Apache Users

### ISSUE THREAD

**Issue by HassanAlthaf** [PatrickLouys/no-framework-tutorial#31]
You've missed out the need to use an `.htaccess` file for Apache users for the Front Controller pattern. The one which works for me is:

<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>
 
    RewriteEngine On
 
    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]
 
    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>

**Comment by HassanAlthaf** [comment]
Argh, the <if> parts are lost. Refer to this pastebin: http://pastebin.com/6HX2y2Be

**Comment by PatrickLouys** [comment]
This is very server specific and not really relevant to the built in server that the tutorial uses. I will consider adding it though and if I do that I'll also add a nginx example config.

**Comment by HassanAlthaf** [comment]
@PatrickLouys Well not everyone is gonna exactly run the built in PHP server like you. :P

**Comment by Zvax** [comment]
+1 for that part should be left to the reader. Nginx for instance has a very different way of managing redirecting non existant urls.

**Comment by Zvax** [comment]
+1 for having to fix that part myself. Imo, no need to clutter this great tutorial with apache or nginx specific code, those are well covered elsewhere on the interwebs.

**Comment by PatrickLouys** [comment]
Agreed

**Comment by oneum** [comment]
Like I asked for help in [#37](https://github.com/PatrickLouys/no-framework-tutorial/issues/37) there is nothig wrong with the guide except I was using the apache2 httpd and I need the .htaccess for this example.

@HassanAlthaf can you please repost the .htaccess content please?
