### ISSUE TITLE
Twig Internationalization

### ISSUE THREAD

**Issue by mr-lanholmes** [PatrickLouys/no-framework-tutorial#34]
Hi @PatrickLouys Thanks for this tutorial, I am able to create a simple web-app. But with the traffic comes from other non-english speaking user.Can you post a simple tutorial n how to integrate Twig with I8n. Thanks!

**Comment by PatrickLouys** [comment]
Hi. I think this would be a little out of scope for the tutorial, I want to keep it as simple as possible while also covering all the important topics.

That being said, I would recommend that you have a look here for the [Twig i18n extension](http://twig.sensiolabs.org/doc/extensions/i18n.html). I haven't used it but it looks like it does what you need.

Cheers,
Pat
