### ISSUE TITLE
hard to apply changes in code from part 05

### ISSUE THREAD

**Issue by oneum** [PatrickLouys/no-framework-tutorial#37]
Hi!

I am followin this tutorial but have problem startin with part 05&06.

Aftre applying changes decribed in 05 part into ./src/Bootstrap.php I always get 404 message, so I am quite confused how exactly should ./src/Bootstrap.php look like.
Can you please make this chapter 05 and 06 more clear?
Thanks!

**Comment by Zvax** [comment]
Hey there. As such, your request seems a bit vague. My gut feeling is you're not redirecting all requests to index.php, which you should know / learn to do. see #31 for details.

If you did, then please specify what you have trouble understanding?
