### ISSUE TITLE
Aura.Cli for command line php

### ISSUE THREAD

**Issue by aaronpeterson** [PatrickLouys/no-framework-tutorial#43]
Any suggestions beyond [Aura.Cli](https://github.com/auraphp/Aura.Cli) for writing php scripts for command line usage?

**Comment by PatrickLouys** [comment]
I am not sure what you are asking. Is the question about a part of the tutorial or unrelated?

**Comment by aaronpeterson** [comment]
Sorry about that.  I thought you were curating a list of common framework features as standalone libraries.  I use Laravel which has a nice CLI tool.  Nevermind.
