### ISSUE TITLE
Add 

### ISSUE THREAD

**Issue by oneum** [PatrickLouys/no-framework-tutorial#46]
Hi there!
First, there is no new issue here, more like request for improving this guide!
Now, I respect all contributors here and I would like to extend/use this guide with [illuminate/database](https://github.com/illuminate/database). Since I need some help here with this, how to properly glue it to existing code?

Thanks

**Comment by PatrickLouys** [comment]
You are free to use what you want, but Active Record goes against SOLID and everything taught in the tutorial. And then things like this...

// Make this Capsule instance available globally via static methods... (optional)
$capsule->setAsGlobal();

I don't think a library which advertises such crappy code has a place in this tutorial.

Cheers
Pat
