### ISSUE TITLE
How i can use database?

### ISSUE THREAD

**Issue by sahibkhan** [PatrickLouys/no-framework-tutorial#49]
Hi Steve how i can using database.you known about my question is that how i can view database record and which packages use for that please share me about that i fellow your tutorial every things work fine .now i m connect to database and fetch the record from database so where i use database class and how i can do that please please

**Comment by PatrickLouys** [comment]
Sorry I did not find time yet to write that chapter.

You can set up a PDO instance that you can then inject into your classes that need to access the database. Have a look at the Table Data Gateway and the Repository pattern if you want some guidance on how a class that accesses the DB should look like.

**Comment by sahibkhan** [comment]
Lot of Thank Bro Steve to responsive me.But bro if you   share me the database libraries just like for Error Handler  filp/whoops you recommend that so there for please share me the libraries

**Comment by PatrickLouys** [comment]
http://php.net/manual/de/book.pdo.php

or if you want to get fancy

http://www.doctrine-project.org/projects/dbal.html

**Comment by sahibkhan** [comment]
Bro Steve i included that libraries doctrine using composer but bro the problem is that where i extend the model classes and where i created the model class and how i connect it to my application if u created that chapter for me just created one database and retrieve or insert data mean small demo about database connectivity its very helpful for me .Thanks Thanks Thanks again and again to response me

**Comment by PatrickLouys** [comment]
I am not "Bro Steve", if you want further help please talk in an appropriate manner.

You don't extend model classes. You should not have any "model classes" at all. Please read again what I wrote earlier (Table Data Gateway/Repository).

**Comment by sahibkhan** [comment]
sorry bro PatrickLouys

**Comment by MrBrax** [comment]
I find it extremely confusing, with nowhere to begin. Done PHP stuff for 12 years but this just makes my brain slow to a crawl.
