### ISSUE TITLE
Could i translate to Turkish?

### ISSUE THREAD

**Issue by coderontheroad** [PatrickLouys/no-framework-tutorial#50]
I saw someone asked for Chinese but because of i haven't seen licence file i want to ask again. Can i translate to Turkish language? And i really suggest putting licence file or information, so if someone want to use your tutorial, he can understand what he can do with it or don't.

**Comment by HassanAlthaf** [comment]
I am guessing it shouldn't be a problem. Go ahead. :)

**Comment by PatrickLouys** [comment]
Of course. Please go ahead.

I did add the MIT license now.
