### ISSUE TITLE
Markdown parsing in 'Dynamic Pages' section

### ISSUE THREAD

**Issue by gbrlmza** [PatrickLouys/no-framework-tutorial#51]
Markdown parsing mentioned in Dynamic Pages but not implemented. Is intentional as an exercise or missing?

**Comment by PatrickLouys** [comment]
Good catch. That was something that I had planned but never got around to writing more chapters...

**Comment by philsown** [comment]
I took a crack at it here:  https://github.com/philsown/noframework/commit/194c082ce5dd413404cba3c72a502c36e375e011
