### ISSUE TITLE
Improve step 4 instructions

### ISSUE THREAD

**Issue by thinsoldier** [PatrickLouys/no-framework-tutorial#52]
Step 4 should say "add the following code before the foreach loop that sends headers" (or similar) instead of
`add the following code between the code snippets from above:`

**Comment by Zvax** [comment]
Nope. 

Setting the content of the response after the headers have been sent makes neither semantical nor logical sense.

Please note that in any practical example, code that executes these three steps would not be procedurally following each other.

**Building the response and sending it are two different steps**.

cheers.
