### ISSUE TITLE
Templating question

### ISSUE THREAD

**Issue by thinsoldier** [PatrickLouys/no-framework-tutorial#55]
If I switched to a different templating system it might have a completely different templating syntax language. So having the change instances of the word "mustache" to something else in a few places in the code would be the smaller part of the amount of work involved in switching templating systems.

Why do you have such a strong opinion on dependency injection vs service locators with only 1 reference link, which supports your view; but have no opinion on templating systems and offer fair billing to both sides by provide 2 good links?

You should be fair and give links to both sides of the argument for DI

http://davidscode.com/blog/2015/04/17/when-does-dependency-injection-become-an-anti-pattern/

**Comment by PatrickLouys** [comment]
There is no argument. Stop your spam.
