### ISSUE TITLE
Question about what goes in the dependency injector and what doesn't.

### ISSUE THREAD

**Issue by thinsoldier** [PatrickLouys/no-framework-tutorial#56]
If the page controller needs the custom InvalidPageException to give the right kind of error message, isn't that a dependency? So should't it be added to the dependency injector settings and the constructor of the page controller instead of using *new*?

**Comment by thinsoldier** [comment]
Also

> Add this at the top of your file:
> use Example\Page\InvalidPageException;
> It is important that you don't forget this step, otherwise it will try to catch the wrong exception (it's looking in the wrong namespace) and thus will never catch it.

If you hadn't told us about this error, is there any way we could have eventually found it on our own? How?

**Comment by PatrickLouys** [comment]
Not everything is a dependency. You should use new for things like value objects (think DateTime) or Exceptions in this case.

See [this](http://programmers.stackexchange.com/questions/257213/value-object-static-factory-or-assisted-injection) for reference.
