### ISSUE TITLE
Route

### ISSUE THREAD

**Issue by hendrixroa** [PatrickLouys/no-framework-tutorial#63]
How add route rest and redirect async data via ajax in the part of router ?

**Comment by philsown** [comment]
Do you mean RESTful routes? Redirect is possible in the patricklouys/http library that is used in the tutorial. The Response object has a `redirect` method described in the docs. With the right response headers, integrating this into Ajax would be pretty simple. You might make another Renderer like the FrontendRenderer in the example, except set it up with some default headers already set, like content type.
