### ISSUE TITLE
Will you continue on your tut?

### ISSUE THREAD

**Issue by MartinSerdar** [PatrickLouys/no-framework-tutorial#64]
Hi Patrick,

I enjoyed your tutorial very much and was looking forward to find out more. Seems like you stopped working on it, right? We have Autumn/Winter 2017 now and the last words were from "cold days 2016". 
I know there are more important things in life but I'd like to know if sth will ever be continued.

**Comment by liederer** [comment]
I would really appreciate it. This no-framework-tutorial is great! 👍

**Comment by PatrickLouys** [comment]
I put my effort into a book instead, which is also in the form of a tutorial. I had to start from scratch because I learned a lot since publishing this tutorial.

See http://patricklouys.com/professional-php/ for more.
